version: '3.9'

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - my_net
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    networks:
      - my_net
    volumes:
      - vi-money-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  vi-money-db-data:

networks:
  my_net:
    external: true
