// REPOSITORIES/SERVICES
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');

// USECASES
export const CREATE_CATEGORY_USE_CASE = Symbol('CREATE_CATEGORY_USE_CASE');
export const FIND_CATEGORIES_BY_USER_ID_USE_CASE = Symbol(
  'FIND_CATEGORIES_BY_USER_ID_USE_CASE',
);
