// REPOSITORIES/SERVICES
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');

// USECASES
export const CREATE_TRANSACTION_USE_CASE = Symbol(
  'CREATE_TRANSACTION_USE_CASE',
);
export const FIND_TRANSACTIONS_BY_USER_ID_USE_CASE = Symbol(
  'FIND_TRANSACTIONS_BY_USER_ID_USE_CASE',
);
